model_list:

  - model_name: qwen3.5-122b-a10b
    litellm_params:
      model: openai/qwen3.5-122b-a10b
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-0363d3e4787e4ab19253e56309e0ff95

  - model_name: qwen3.5-plus
    litellm_params:
      model: openai/qwen3.5-plus
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-0363d3e4787e4ab19253e56309e0ff95

  - model_name: glm-image
    litellm_params:
      model: openai/GLM-Image
      api_base: https://open.bigmodel.cn/api/paas/v4
      api_key: 4326f6d62899f7262aca39ef10a0aebd.WqS1NPb82t5ylEjD

  - model_name: qwen3-reranker-0.6b
      litellm_params:
        model: cohere/qwen3-reranker:0.6B
        api_base: http://127.0.0.1:12435/v1
        api_key: "not-needed"
general_settings:
  master_key: sk-global-litellm-key
  store_model_in_db: true
litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
