services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - DATABASE_URL=postgresql://postgres:wangjian020426@localhost:5432/litellm
      - LITELLM_MASTER_KEY=sk-xb.cat.sleep.campus
      - UI_USERNAME=admin
      - UI_PASSWORD=password123
    command: [ "--config", "/app/config.yaml", "--detailed_debug" ]
    restart: always
