server:
  port: 8888
  servlet:
    context-path: /campus/help
spring:
  application:
    name: form_wall
  profiles:
    active: dev
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web

      PUT ai_chat_knowledge
      {
        "mappings": {
          "properties": {
            "id": {
              "type": "keyword"
            },
            "content": {
              "type": "text",
              "analyzer": "standard"
            },
            "embedding": {
              "type": "dense_vector",
              "dims": 1536,
              "index": true,
              "similarity": "cosine"
            },
            "session_id": {
              "type": "keyword"
            },
            "create_time": {
              "type": "date"
            }
          }
        }
      }
